version: "3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - db
    command: python main.py
    container_name: fastapi_app
    networks:
      - app-network

  db:
    image: postgres:16.1
    container_name: fastapi_postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=567234
      - POSTGRES_DB=hw02
    # ports:
    #   - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
